### ISSUE TITLE
Rename package to autoware_ndt_omp

### ISSUE THREAD

**Issue by esteve** [tier4/ndt_omp#67]
There is an ongoing effort to prefix all packages with `autoware_` to prevent clashes with existing packages and to signal that these are packages that are part of the Autoware project.

In fact, because this package is still named `ndt_omp` and the original upstream package is already in the ROS index, our buildfarm is can't any package that depends on `ndt_omp` properly (see https://github.com/autowarefoundation/autoware/issues/4569). For now, I'm ignoring  `ndt_omp` and `ndt_scan_matcher` in the buildfarm, but it'd be great if at least `ndt_omp` is renamed soon.

**Comment by esteve** [comment]
@SakodaShintaro @YamatoAndo @mitsudome-r @xmfcx I remember that it was planned to integrate `ndt_omp` inside `autoware_ndt_scan_matcher`, but this repository is still separate. Unfortunately because the package in this repository has the same name as in the ROS index, it's still breaking the builds in https://github.com/autowarefoundation/autoware-deb-packages/pull/98

For now I'll ignore `autoware_ndt_scan_matcher` in the builds, but we need to find a way to avoid duplicate package names:

 - We rename `ndt_omp` to something else (e.g. `autoware_ndt_omp`, `tier4_ndt_omp`, etc.)
 - We integrate the code from `ndt_omp` into `autoware_ndt_scan_matcher` and remove the dependency for `ndt_omp`

**Comment by SakodaShintaro** [comment]
Please see https://github.com/autowarefoundation/autoware.universe/pull/8912#discussion_r1772670302

**Comment by esteve** [comment]
@SakodaShintaro oh, sorry I missed that comment, I'll reply there. Thanks for the link

**Comment by YamatoAndo** [comment]
This issue has been resolved by moving `ndt_omp` into `autoware_ndt_scan_matcher`, so I will close this issue.
https://github.com/autowarefoundation/autoware.universe/pull/8912
